CREATE TABLE IF NOT EXISTS offices
(
    index   INT          NOT NULL,
    name    VARCHAR(128) NOT NULL,
    address VARCHAR(512) NOT NULL,
    CONSTRAINT post_offices_pk PRIMARY KEY (index)
);

CREATE TABLE IF NOT EXISTS posts
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type    VARCHAR(32)                             NOT NULL,
    index   INT                                     NOT NULL,
    address VARCHAR(512)                            NOT NULL,
    name    VARCHAR(256)                            NOT NULL,
    status  VARCHAR(64)                             NOT NULL,
    CONSTRAINT posts_pk PRIMARY KEY (id),
    CONSTRAINT posts_offices_null_fk FOREIGN KEY (index) REFERENCES offices (index)
);

CREATE TABLE IF NOT EXISTS visits
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    post_id        BIGINT NOT NULL,
    index          INT    NOT NULL,
    arrival_date   TIMESTAMP,
    departure_date TIMESTAMP,
    CONSTRAINT visits_pk PRIMARY KEY (id),
    CONSTRAINT visits_posts_null_fk FOREIGN KEY (post_id) REFERENCES posts (id),
    CONSTRAINT visits_offices_null_fk FOREIGN KEY (index) REFERENCES offices (index)
);
